name: Update
on:
  push:
    branches:
      - main

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        submodules: true

    # Update references
    - name: 🌱 Sync submodules
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "🌱 Sync submodules" && git push || echo "No changes to commit"
